[workspace]
members = ["tiny-wgs84", "nav-math", "strapdown", "trajectory-sim"]
default-members = ["tiny-wgs84", "nav-math", "strapdown", "trajectory-sim"]

exclude = ["target/*"]
resolver = "2"


[workspace.package]
version = "0.1.0"
authors = ["Andrei Gherghescu <andrei-ng@protonmail.com>"]
description = "Strapdown Inertial Navigation System library"
edition = "2021"
name = "strapdown-ins"
license = "MIT"
repository = "https://github.com/andrei-ng/strapdown-ins"
homepage = "https://github.com/andrei-ng/strapdown-ins"
documentation = "https://docs.rs/strapdown-ins"
keywords = ["navigation", "ins", "inertial"]
readme = "README.md"
categories = ["algorithms", "science", "science::geo", "science::robotics"]
